name: app-server
region: sfo
services:
  - dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: intrepion/intrepion-saying-hello-json-rpc-server-csharp-dotnet-webapi
    health_check:
      http_path: /HealthCheck
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    name: server
    routes:
      - path: /
    source_dir: /
